package org.silcongo.autopds

import org.silcongo.autopds.util.*

class ClipMVideo extends Clip
{
	//AEFF_MVIDEO_A_TRACK/AEFF_MVIDEO_B_TRACK:
	//<CLIP ID="1" IDREF="90" NAME="" START="560226893" STOP="610276943" SCENESTART="0" SCENESTOP="0" MEDIASTART="0" MEDIASTOP="5006005" MUTE="FALSE" STRETCHMODE="STRETCH" PANOVISIONMODE="0">

	def panZoom
	def clipMAudio
	
	public ClipMVideo(uid, mediaObj, startTime, dur=-1)
	{
		id = uid
		mediaObject = mediaObj
		idRef = mediaObject.id
		name = mediaObject.name

		if(dur == -1){mediaDuration = mediaObject.duration}
		else{mediaDuration = dur}
		duration = mediaDuration

		start = startTime
		
		if(mediaObject instanceof ColorObject)
		{
			stretchMode = "STRETCH"
		}
		else if(mediaObject instanceof VideoObject)
		{
			aspectRatioX = -1
			aspectRatioY = -1
			stretchMode = "PRESERVEASPECTRATIO"
			autoSetFocus = true
		}
		else
		{
			aspectRatioX = 0
			aspectRatioY = 0
			stretchMode = "PRESERVEASPECTRATIO"
			autoSetFocus = true
		}
		
		//ClipExtraData
		alias = mediaObject.name
		
		panZoom = new PanZoom()
		
		recalculateStopTimes()
	}
	
	public void recalculateStopTimes()
	{
		mediaStart = startOffset
		mediaStop = mediaDuration - stopOffset
		
		duration = mediaStop - mediaStart
		
		stop = start + duration
		
		if(mediaObject instanceof VideoObject)
		{
			sceneStop = mediaDuration
		}
	}
	
	public String toString()
	{
		def output = new StringBuilder()

		use(DataFormat)
		{
			output << """<CLIP ID="$id" IDREF="$idRef" NAME="$name" START="${start.i()}" STOP="${stop.i()}" SCENESTART="${sceneStart.i()}" SCENESTOP="${sceneStop.i()}" MEDIASTART="${mediaStart.i()}" MEDIASTOP="${mediaStop.i()}" MUTE="${mute.B()}" STRETCHMODE="$stretchMode" PANOVISIONMODE="$panovisionMode">
<CLIP_EXTRA_DATA ID="0">
<PARAM NAME="VIDEO_EAGLEVISION_STRENGTH" VALUETYPE="FLOAT" VALUE="0.000000"/>
<PARAM NAME="VIDEO_EAGLEVISION_FLAG" VALUETYPE="INT" VALUE="0"/>
<PARAM NAME="VIDEO_MOTIONPARAM" VALUETYPE="INT" VALUE="${panZoom.toString()}"/>
<PARAM NAME="VIDEO_MOTIONPARAM_SIZE" VALUETYPE="INT" VALUE="${panZoom.size()}"/>
<PARAM NAME="VIDEO_EAGLEVISION_MODE" VALUETYPE="UNSIGNED_INT" VALUE="0"/>
<PARAM NAME="VIDEO_STABLIZER_MODE" VALUETYPE="UNSIGNED_INT" VALUE="0"/>
<PARAM NAME="VIDEO_STABLIZER_TOLERANCE" VALUETYPE="UNSIGNED_INT" VALUE="0"/>
<PARAM NAME="VIDEO_STABLIZER_ANGLE" VALUETYPE="FLOAT" VALUE="0.000000"/>
<PARAM NAME="VIDEO_ASPECTRATIO_X" VALUETYPE="INT" VALUE="$aspectRatioX"/>
<PARAM NAME="VIDEO_ASPECTRATIO_Y" VALUETYPE="INT" VALUE="$aspectRatioY"/>
<PARAM NAME="VIDEO_DENOISE_MODE" VALUETYPE="UNSIGNED_INT" VALUE="0"/>
<PARAM NAME="VIDEO_DENOISE_STRENGTH" VALUETYPE="FLOAT" VALUE="0.000000"/>
<PARAM NAME="VIDEO_REVERSE_FLAG" VALUETYPE="BOOL" VALUE="FALSE"/>
<PARAM NAME="VIDEO_TTMOTION_FLAG" VALUETYPE="BOOL" VALUE="FALSE"/>
<PARAM NAME="VIDEO_TTHD_MODE" VALUETYPE="INT" VALUE="0"/>
<PARAM NAME="VIDEO_ROTATE_ANGLE" VALUETYPE="INT" VALUE="0"/>
<PARAM NAME="VIDEO_TTHD_STRENGTH" VALUETYPE="FLOAT" VALUE="0.000000"/>
<PARAM NAME="VIDEO_USER_DATA_ALIAS" VALUETYPE="STRING" VALUE="$alias"/>
<PARAM NAME="VIDEO_USER_DATA_ORI_FILENAME" VALUETYPE="STRING" VALUE="${mediaObject.src}"/>
<PARAM NAME="VIDEO_USER_DATA_APPLY_MAGIC_CLEAN" VALUETYPE="BOOL" VALUE="FALSE"/>
<PARAM NAME="VIDEO_USER_DATA_AUTOFIX_FLAG" VALUETYPE="INT" VALUE="0"/>
<PARAM NAME="VIDEO_USER_DATA_APPLY_MAGIC_MOTION" VALUETYPE="BOOL" VALUE="${panZoom.getApply()}"/>
<PARAM NAME="VIDEO_USER_DATA_AUTO_SET_FOCUS" VALUETYPE="BOOL" VALUE="${autoSetFocus.B()}"/>
<PARAM NAME="VIDEO_USER_DATA_MAGIC_MOTION_X_COORD" VALUETYPE="FLOAT" VALUE="0.000000"/>
<PARAM NAME="VIDEO_USER_DATA_MAGIC_MOTION_Y_COORD" VALUETYPE="FLOAT" VALUE="0.000000"/>
<PARAM NAME="VIDEO_USER_DATA_MAGIC_MOTION_WIDTH" VALUETYPE="FLOAT" VALUE="0.000000"/>
<PARAM NAME="VIDEO_USER_DATA_MAGIC_MOTION_HEIGHT" VALUETYPE="FLOAT" VALUE="0.000000"/>
<PARAM NAME="VIDEO_USER_DATA_MAGIC_MOTION_STYLE" VALUETYPE="INT" VALUE="${panZoom.getStyle()}"/>
<PARAM NAME="VIDEO_USER_DATA_MAGIC_REFOCUS_LEVEL" VALUETYPE="INT" VALUE="0"/>
<PARAM NAME="VIDEO_USER_DATA_APPLY_MAGIC_ENHANCE" VALUETYPE="BOOL" VALUE="FALSE"/>
<PARAM NAME="VIDEO_USER_DATA_STABILIZER_LEVEL" VALUETYPE="UNSIGNED_INT" VALUE="0"/>
<PARAM NAME="VIDEO_USER_DATA_STAB_REAL_TOLRANCE" VALUETYPE="UNSIGNED_INT" VALUE="0"/>
<PARAM NAME="VIDEO_USER_DATA_STAB_SHADOW_TOLRANCE" VALUETYPE="UNSIGNED_INT" VALUE="0"/>
<PARAM NAME="VIDEO_USER_DATA_IMAGE_RESIZE" VALUETYPE="BOOL" VALUE="FALSE"/>
<PARAM NAME="VIDEO_USER_DATA_SHOW_TIMECODE" VALUETYPE="BOOL" VALUE="FALSE"/>
<PARAM NAME="AEFF_VIDEO_USER_DATA_POWER_TOOL" VALUETYPE="INT" VALUE="0"/>
<PARAM NAME="VIDEO_USER_DATA_SPEED_FACTOR" VALUETYPE="FLOAT" VALUE="1.000000"/>
<CLIP_EXTRA_DATA_MAGICEFFECT ID="0"/>
</CLIP_EXTRA_DATA>
</CLIP>"""
		}
		
		return output.toString()
	}
}